name: AutoPost Facebook Reels via Telegram Input

on:
  schedule:
    - cron: "0 */6 * * *"  # Setiap 6 jam
  workflow_dispatch:

jobs:
  autopost:
    runs-on: ubuntu-latest

    env:
      FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
      FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Restore cache for posted_media.json
      id: cache-posted
      uses: actions/cache@v3
      with:
        path: posted_media.json
        key: posted-media-v1

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create empty posted_media.json if not exists
      run: |
        if [ ! -f posted_media.json ]; then
          echo "{}" > posted_media.json
          echo "✅ created new posted_media.json"
        else
          echo "ℹ️ existing posted_media.json preserved"
        fi

    - name: Run AutoPost script
      run: python main.py

    - name: Save updated posted_media.json to cache
      if: always()
      run: echo "✅ posted_media.json has been updated."
