# .github/workflows/autopost.yml
name: AutoPost Facebook Reels via Telegram Input

on:
  schedule:
    - cron: "0 */6 * * *" # Jalankan setiap 6 jam. Ubah menjadi "0 */24 * * *" untuk 1 hari sekali.
  workflow_dispatch: # Memungkinkan trigger manual dari GitHub UI

jobs:
  autopost:
    runs-on: ubuntu-latest

    env:
      FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
      FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }} # CHAT_ID yang Anda gunakan untuk mengirim video ke bot

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run AutoPost Script
      run: python main.py
