name: AutoPost Facebook Reels

on:
  workflow_dispatch: # Memungkinkan pemicuan manual dari UI GitHub Actions
  schedule:
    - cron: '0 */6 * * *' # Menjalankan setiap 6 jam (pada menit ke-0, setiap 6 jam)

jobs:
  run-autopost:
    runs-on: ubuntu-latest # Menjalankan di lingkungan Ubuntu terbaru

    steps:
    - name: Checkout repository # Mengambil kode dari repositori GitHub
      uses: actions/checkout@v4
      with:
        # Penting: Menggunakan personal access token untuk izin menulis ke repositori
        # Ganti YOUR_GITHUB_TOKEN_SECRET dengan nama secret GitHub Anda
        token: ${{ secrets.REPO_ACCESS_TOKEN }} 

    - name: Set up Python # Mengatur lingkungan Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Menentukan versi Python yang akan digunakan

    - name: Install dependencies # Menginstal dependensi Python dari requirements.txt
      run: |
        pip install -r requirements.txt

    - name: Install FFmpeg # Menginstal FFmpeg, yang diperlukan oleh video_utils.py
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Run AutoPost Script # Menjalankan skrip utama
      env: # Mengatur variabel lingkungan dari GitHub Secrets
        FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
        FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python main.py

    - name: Commit and Push changes # Meng-commit dan me-push file persistensi ke repositori
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add posted_media.json last_update_offset.txt
        # '|| true' digunakan agar langkah ini tidak gagal jika tidak ada perubahan untuk di-commit
        git commit -m "AutoPost: Update posted media and offset" || true 
        git push
      env:
        # Pastikan REPO_ACCESS_TOKEN adalah Personal Access Token dengan izin 'repo'
        GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }} 
