# .github/workflows/autopost.yml
name: AutoPost Facebook Reels via Telegram Input

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  autopost:
    runs-on: ubuntu-latest

    env:
      FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
      FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # --- PERUBAHAN DI SINI ---
    - name: Clean previous offset file (for debugging only)
      run: rm -f last_update_offset.txt
      # Hapus langkah ini setelah bot berfungsi seperti yang diharapkan
      # agar bot tidak terus-menerus memproses ulang pesan lama
    # --- AKHIR PERUBAHAN ---

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run AutoPost Script
      run: python main.py
